#!/bin/bash
for i in bashrc gitconfig gitignore vimrc vim tmux.conf i3 i3status.conf xsession
do
	rm -rf $HOME/.$i;
	ln -s $HOME/dotfiles/$i $HOME/.$i;
done;

rm -rf ~/.config/awesome
ln -s $HOME/dotfiles/awesome $HOME/.config/awesome
